name: Kotlin CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
      - name: Build with Gradle
        run: chmod +x gradlew && ./gradlew build
      - name: Run tests
        run: chmod +x gradlew && ./gradlew test