name: Kotlin CI

on:
  push:
    branches:
      - master # Only run build on push to master branch
  pull_request:
    branches:
      - master # Only run build for pull requests targeting the master branch

permissions:
  checks: write
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BOT_API_KEY: ${{ secrets.BOT_API_KEY }}
      BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
      BOT_CREATOR_ID: ${{ secrets.BOT_CREATOR_ID }}
      WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JUnit Tests
          path: build/test-results/test/*.xml
          reporter: java-junit
          fail-on-error: true